In [1]:
import torch
# J'importe les librairies necessaires

In [2]:
import pytorch_pretrained_bert as bert


In [4]:
#embeddingsModel = "bert-base-multilingual-cased"
embeddingsModel = "bert-base-uncased"
# voir liste des modèles ici https://github.com/huggingface/pytorch-pretrained-BERT#overview

In [5]:
embeddings=bert.BertModel.from_pretrained(embeddingsModel)
# J'importe les embeedings depuis le cache (ou le net si on ne les a pas déjà)

100%|██████████| 407873900/407873900 [00:16<00:00, 24409159.03B/s]


In [6]:
embeddings.eval()

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): BertLayerNorm()
    (dropout): Dropout(p=0.1)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): BertLayerNorm()
            (dropout): Dropout(p=0.1)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=

In [7]:
tokenizer=bert.BertTokenizer.from_pretrained(embeddingsModel,do_lower_case=False)
# Je fabrique un tokenizer correspondant à mon modèle d'embeddings
## I make a tokenizer corresponding to my embeddings template

The pre-trained model you are loading is an uncased model but you have set `do_lower_case` to False. We are setting `do_lower_case=True` for you but you may want to check this behavior.
100%|██████████| 231508/231508 [00:00<00:00, 790461.64B/s]


In [8]:
tokens=["[CLS]"] + tokenizer.tokenize("May the force be with you.") + ["[SEP]"] + tokenizer.tokenize("No, I am your father.")+ ["[SEP]"]
# Je tokenize mon texte   --------- # I tokenize my text


# je mets une balise [CLS] en début de texte et une balise [SEP] en fin de phrase 
# # I put a [CLS] tag at the beginning of the text and a [SEP] tag at the end of the sentence
print(tokens) # affichage
tokens2=["[CLS]"] + tokenizer.tokenize("The little cat is black.") + ["[SEP]"]
# Je tokenize mon texte
# je mets une balise [CLS] en début de texte et une balise [SEP] en fin de phrase 
print(tokens2) # affichage


['[CLS]', 'may', 'the', 'force', 'be', 'with', 'you', '.', '[SEP]', 'no', ',', 'i', 'am', 'your', 'father', '.', '[SEP]']
['[CLS]', 'the', 'little', 'cat', 'is', 'black', '.', '[SEP]']


In [9]:

# I transform my tokens into identifiers (reminder: pytorch only handles integers)
# Je transforme mes tokens en identifiants (rappel : pytorch ne manipule que des entiers)

ids=tokenizer.convert_tokens_to_ids(tokens)
print(ids) # Display
ids2=tokenizer.convert_tokens_to_ids(tokens2)
# Je transforme mes tokens en identifiants (rappel : pytorch ne manipule que des entiers)

# Je transforme mes tokens en identifiants (rappel : pytorch ne manipule que des entiers)
print(ids2) # affichage

[101, 2089, 1996, 2486, 2022, 2007, 2017, 1012, 102, 2053, 1010, 1045, 2572, 2115, 2269, 1012, 102]
[101, 1996, 2210, 4937, 2003, 2304, 1012, 102]


In [11]:

# Je transforme mes ids en tenseur pytorch (représentation en long soit 64 bits de précision, voir https://pytorch.org/docs/stable/tensors.html)
# I transform my ids into a pytorch tensor (representation in length is 64 bits of precision, see https://pytorch.org/docs/stable/tensors.html)

ids=torch.tensor(ids, dtype=torch.long)
print(ids) # affichage


# Je transforme mes ids en tenseur pytorch (représentation en long soit 64 bits de précision, voir https://pytorch.org/docs/stable/tensors.html)
# I transform my ids into a pytorch tensor (representation in length is 64 bits of precision, see https://pytorch.org/docs/stable/tensors.html)


ids2=torch.tensor(ids2, dtype=torch.long)


print(ids2) # Display

tensor([ 101, 2089, 1996, 2486, 2022, 2007, 2017, 1012,  102, 2053, 1010, 1045,
        2572, 2115, 2269, 1012,  102])
tensor([ 101, 1996, 2210, 4937, 2003, 2304, 1012,  102])


In [12]:
# unsqueeze is a function that adds a dimension of size 1 in the tensor.
# Some pytorch functions (including embeddings below) expect to have input
# 3D tensors while at the moment we have 2D tensors.
# So, we use unsqueeze to add a dimension of size 1 to the tensor.

ids=ids.unsqueeze(0)
print(ids)
ids2=ids2.unsqueeze(0)
print(ids2)



# unsqueeze est une fonction qui ajoute une dimension de taille 1 dans le tenseur. 
# Certaines fonctions pytorch (dont embeddings ci-dessous) s'attendent à avoir des tenseurs 3D en entrée alors que nous avons pour l'instant des tenseurs en 2D.
# ainsi, on utilise unsqueeze pour rajouter une dimension de taille 1 au tenseur.

tensor([[ 101, 2089, 1996, 2486, 2022, 2007, 2017, 1012,  102, 2053, 1010, 1045,
         2572, 2115, 2269, 1012,  102]])
tensor([[ 101, 1996, 2210, 4937, 2003, 2304, 1012,  102]])


In [16]:

# calcul de l'ensemble des embeddings du texte 1
# calculation of all the embeddings of the text 1

Embeddings_phrase_1, _=embeddings(ids,output_all_encoded_layers=False)


print(Embeddings_phrase_1.size())

torch.Size([1, 17, 768])


In [19]:
Embeddings_phrase_2, _=embeddings(ids2,output_all_encoded_layers=False)
# calcul de l'ensemble des embeddings du texte 2
Embeddings_phrase_2 #affichage
print(Embeddings_phrase_2.size())

torch.Size([1, 8, 768])


In [20]:
cos=torch.nn.CosineSimilarity(dim=0, eps=1e-6)

# I want to make a cosine similarity, I make the object that will allow me
# Je veux faire une similarité cosinus, je fabrique l'objet qui me le permettra

In [21]:
cos(Embeddings_phrase_1[0,0],Embeddings_phrase_2[0,0])

# I make the cosine similarity between my two texts. Embeddings_phrase_1 [0,0] represents the embeddings of [CLS] which by construction is the embeddings of the complete sentence


# I find 0.4907
# Je fais la similarité cosinus entre mes deux textes. Embeddings_phrase_1[0,0] représente l'embeddings de [CLS] qui par construction est l'embeddings de la phrase complète
# Je trouve 0,4907

tensor(0.8992, grad_fn=<DivBackward0>)